name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy: 
      matrix:
        include:
          - os: macos-latest
            name: macos_x86_64
            target: x86_64-apple-darwin
          - os: macos-latest
            name: macos_aarch64
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            name: linux_x86_64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            name: linux_aarch64
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            name: windows_x86_64
            target: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v3
    - name: Install rust version
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: ${{matrix.toolchain}}
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose --release --features=expensive_tests
    - name: Build Release
      run: cargo build --verbose --release
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-${{matrix.name}}"
        prerelease: false
        title: "Latest Build ${{matrix.name}}"
        files: |
          target/release/solipath.exe
          target/release/download_verifier.exe
          target/release/solipath.so
          target/release/download_verifier.so
          target/release/solipath
          target/release/download_verifier
